workflow:
  - ".github/**"

build-gradle:
  - "gradle/**"
  - "build.gradle.kts"
  - "settings.gradle.kts"
  - "*/build.gradle.kts"
  - "*/settings.gradle.kts"
  - "gradle.properties"
  - ".gitignore"

docker:
  - "docker-compose.yml"
  - "*/docker-compose.yml"
  - "docker-compose.dev.yml"
  - "*/docker-compose.dev.yml"
  - "Dockerfile"
  - "*/Dockerfile"
  - ".dockerignore"
  - "*/.dockerignore"

env:
  - ".env"
  - "*/.env"

core:
  - "src/main/*"

test:
  - "**/src/test/*"
  - "**/*/*Test*"

meta:
  - "**/META-INF/*"

frontend:
  - frontend/**/*
  - any: ['*.vue']
  - any: ['*.js']

