# docker-compose up --d --build --force-recreate redis

version: "3.7"
services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    command: redis-server --requirepass 123456
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - colaba_default
    volumes:
      - redis-data:/data
networks:
  colaba_default:
volumes:
  redis-data:
